# docker compose up --build
services:

  web:
    build: ./web
    ports:
      - "3000:3000"

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cool_app
